### ISSUE TITLE
Unable to add contract to new Dapphero project

### ISSUE THREAD

**Issue by Ro5s** [raid-guild/dapphero-dashboard#5]
Excited to see dapphero community project here. 

I was playing with the [dashboard deployment](https://pryyc3oismlyway5wivf6b47ttgspn3wmbp4oe5z6tdvdxexnyqa.arweave.net/fHGBbciTF4sDHbIqXwefnM0nt3ZgX8cTufTHUdyXbiA/) and noticed an issue with adding a smart contract to a new project (mainnet).

Have you noticed similar issues recently? 

![image](https://user-images.githubusercontent.com/41117279/116700017-4999c400-a994-11eb-9814-c5bec5ad80fb.png)

**Comment by Ro5s** [comment]
to clarify for issue, I am also not able to successfully upload a contract (tx not mined on arweave): 
![image](https://user-images.githubusercontent.com/41117279/117689394-b3ca1a00-b187-11eb-835d-e4ef4fca0254.png)

![image](https://user-images.githubusercontent.com/41117279/117689308-98f7a580-b187-11eb-84a5-66c152c4db8d.png)

**Comment by Ro5s** [comment]
Also, if anyone can help get things setup (bug or ux issue?), LexDAO has given me 0.5 ETH in bounty for dapphero reboot community: https://app.daohaus.club/dao/0x64/0x58234d4bf7a83693dc0815d97189ed7d188f6981/proposals/10

**Comment by ECWireless** [comment]
Hey @Ro5s I'm just seeing this issue, so apologies on the lack of response! I'll try to tackle this now though. Could you link the contract you are trying to add to DappHero?

**Comment by Ro5s** [comment]
hey @ECWireless thanks for following up here! Here is a contract I am trying to add to test things out: [0x43B644a01d87025c9046F12eE4cdeC7E04258eBf](https://etherscan.io/address/0x43b644a01d87025c9046f12ee4cdec7e04258ebf#code). I appreciate you taking a look 🙏 ~~

**Comment by ECWireless** [comment]
~~@Ro5s it actually looks like the contract is working for me 🤔 maybe Arweave was just taking a while to mine the transaction? If you check the dashboard now, do you see the contract?~~ <-- scratch that. It worked for me only because I'm using a new deployment. Does this `dev` deployment work for you? https://arweave.net/i1nqXw9vuDV6hAVlNWyLzXZ7EHVKwxk5p85149eYZSE

^ it's still a work in progress, so UX is so so. Main difference is that you have to click "upload" on your contract before saving.

**Comment by ECWireless** [comment]
This issue is likely linked to #8

**Comment by Ro5s** [comment]
thanks for checking this issue @ECWireless So if I can understand better, I should use a small abi file for now?

**Comment by ECWireless** [comment]
> thanks for checking this issue @ECWireless So if I can understand better, I should use a small abi file for now?

Oh, no sorry, was saying try this deployment with the same ABI, and let me know if it works for you: https://arweave.net/i1nqXw9vuDV6hAVlNWyLzXZ7EHVKwxk5p85149eYZSE

**Comment by Ro5s** [comment]
@ECWireless ah, I see. I just tried reuploading my ABI to contracts, as well as creating a new project, but still saw Arweave tx mining issues, to add to review 🙏

**Comment by ECWireless** [comment]
> @ECWireless ah, I see. I just tried reuploading my ABI to contracts, as well as creating a new project, but still saw Arweave tx mining issues, to add to review 🙏

Could you check if the contract is appearing now? It looks like the transaction has gone through: https://viewblock.io/arweave/tx/TCstXbAXRKMhvSYlYEteGTuhViuyQma3tuKskF5I5Js

**Comment by Ro5s** [comment]
hey @ECWireless Thanks for taking a look! **EDIT: I have found the contract using your update link. I think the remaining issue might involve `Project Script Tag` not being mined on Arweave.

**Comment by ECWireless** [comment]
> hey @ECWireless Thanks for taking a look! **EDIT: I have found the contract using your update link. I think the remaining issue might involve `Project Script Tag` not being mined on Arweave.

Got it! Good news at least with the first half. I can look into the remaining issue today.

**Comment by ECWireless** [comment]
@Ro5s alright, I think I've got this officially fixed. Try this deployment on for size: https://arweave.net/_2lVWgpvPI-cMAaM7-_75j6Tn7304VQoJ9SW8zT5S20

If it works, I'll go ahead and merge this update into `master`

**Comment by ECWireless** [comment]
@Ro5s can you confirm if [this link]( https://arweave.net/_2lVWgpvPI-cMAaM7-_75j6Tn7304VQoJ9SW8zT5S20) works for you? Will hold off another 2 weeks before merging the changes and closing this issue
